- name: Install software
  package: name={{ item }} state=installed
  become: true
  with_items:
    - byobu
    - firefox
    - git-gui
    - gitg
    - gitk
    - kdiff3
    - keepass2
    - redshift-gtk
    - tig