- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yaml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yaml"
    - "../vars/default.yml"

- name: Install software
  package: name={{ item }} state=installed
  become: true
  with_items:
    - firefox
    - git-gui
    - gitg
    - gitk
    - kdiff3
    - "{{ keepass_package_name }}"
    - redshift-gtk
