- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yaml"
    - "{{ ansible_os_family }}.yml"
    - "default.yaml"
    - "default.yml"

- name: Install command line utilities
  package: name={{ item }} state=installed
  become: true
  with_items:
    - tig
    - htop
    - iotop
    - iftop
    - nmap
    - "{{ the_silver_searcher_package_name }}"

- name: Install GUI software
  package: name={{ item }} state=installed
  become: true
  with_items:
    - firefox
    - git-gui
    - gitg
    - gitk
    - kdiff3
    - "{{ keepass_package_name }}"
    - redshift-gtk
    - aspell-en
