# ~/.bashrc: executed by bash(1) for non-login shells.
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Launch byobu
_byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true

[ -r ~/.byobu/prompt ] && . ~/.byobu/prompt   #byobu-prompt#

# Use vim as the standard editor
export VISUAL=vim
export EDITOR="$VISUAL"

export PATH=$PATH:$HOME/.local/bin:$HOME/bin

# Add npm local prefix to path
export PATH="$HOME/.npm/bin:$PATH"

# Add pyenv with virtualenv to path
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

